version: '3'

services:
    mysqlsrv:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_USER: "root"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "relatorio_producao"
        ports:
            - "3306:3306"
        hostname: mysql
        networks:
            - mysql-compose-network
      
    copadubo-service:
        container_name: service
        image: 130593/copadubo-service:latest
        ports:
            - "8080:8080"
        hostname: copadubo-service
        depends_on:
            - mysqlsrv
      
      
    copadubo-view:
        container_name: view
        image: 130593/copadubo-view:latest
        ports:
            - "3000:3000"
        links:
            - copadubo-service
        environment:
            URL_SERVICE: "http://192.168.99.100:8080"
        hostname: view
        depends_on:
            - mysqlsrv
            - copadubo-service
networks: 
  mysql-compose-network:
    driver: bridge