apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-service-deployment
  namespace: integracao
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: service-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1