apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-deployment
spec:
  template:
    metadata:
      labels:
       name: aplicacao-pod
    spec:
      containers:
        - name: container-view
          image: 130593/copadubo-view:latest
          ports:
            - containerPort: 3000
