apiVersion: apps/v1
kind: Deployment
metadata:
  name: copadubo-deployment
  labels:
    app: copadubo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copadubo
  template:
    metadata:
      labels:
        app: copadubo
    spec:
      containers:
      - name: copadubo-view
        image: 130593/copadubo-view:latest
        ports:
        - containerPort: 3000
